// example of custom API
import groovy.json.JsonSlurperClassic 

@NonCPS
def jsonParse(def json) {
    new groovy.json.JsonSlurperClassic().parseText(json)
}

def repo = "hamzaessabri/jenkins-course"

def pr = httpRequest authentication: 'boomi_auth', contentType: 'APPLICATION_JSON', httpMode: 'POST', requestBody: 'grant_type=client_credentials', url: 'http://localhost:9090/ws/rest/disco/v1/albums'
//def accessToken = jsonParse(token.content).access_token
//def pr = httpRequest customHeaders: [[maskValue: true, name: 'Authorization', value: 'Bearer ' + accessToken]], url: "http://localhost:9090/ws/rest/disco/v1/albums"

for (p in jsonParse(pr.content).values) { 
    println(p.source.branch.name)
}
