node {
            stage('Packaging') {
               build job: 'Create Packages', parameters: [[$class: 'StringParameterValue', name: 'processNames', value: processNames], [$class: 'StringParameterValue', name: 'notes', value: notes], [$class: 'StringParameterValue', name: 'packageVersion', value: packageVersion]]
            }
            stage('Deploy to Dev') {
                build job: 'Deploy Packages', parameters: [[$class: 'StringParameterValue', name: 'processNames', value: processNames], [$class: 'StringParameterValue', name: 'env', value: Dev_env], [$class: 'StringParameterValue', name: 'notes', value: notes], [$class: 'StringParameterValue', name: 'packageVersion', value: packageVersion]]            
            }
            stage('Execute Dev Process') {
                build job: 'executeProcesses', parameters: [[$class: 'StringParameterValue', name: 'processNames', value: ProcessNames], [$class: 'StringParameterValue', name: 'atomName', value: atomName], [$class: 'StringParameterValue', name: 'atomType', value: atomType]]              
            }
            stage('Validate Test Process') {
                build job: 'Query Execution Record', parameters: [[$class: 'StringParameterValue', name: 'processName', value: ProcessNames], [$class: 'StringParameterValue', name: 'env', value: Dev_env], [$class: 'StringParameterValue', name: 'atomName', value: atomName], [$class: 'StringParameterValue', name: 'checkStatus', value: 'true']]                
            }     
            stage('sonar-scanner'){
            def scannerHome = tool name: 'Boomi Sonar', type: 'hudson.plugins.sonar.SonarRunnerInstallation'
            withCredentials([string(credentialsId: 'sonarToken', variable: 'sonarToken')]) {
              sh "${scannerHome}/bin/sonar-scanner -e -Dsonar.projectKey=BoomiSonar  -Dsonar.sources=${WORKSPACE} -Dsonar.login=${sonarToken}"
                        }
            }
            stage('Deploy to Prod') {
                build job: 'Deploy Packages',propagate: false, parameters: [[$class: 'StringParameterValue', name: 'processNames', value: processNames], [$class: 'StringParameterValue', name: 'env', value: PromotionEnv], [$class: 'StringParameterValue', name: 'notes', value: notes], [$class: 'StringParameterValue', name: 'packageVersion', value: packageVersion]]            
            }
}
